param([string]$Chrome='C:\Program Files\Google\Chrome\Application\chrome.exe')
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
$report=Join-Path $root 'reports\images-mobile-dom-full-bleed-heading'
$shots=Join-Path $report 'screenshots';New-Item -ItemType Directory -Force $shots|Out-Null
$page='/school/110041107-%EA%B2%BD%EB%8F%99%EA%B3%A0%EB%93%B1%ED%95%99%EA%B5%90/%EC%98%81%EC%96%B4%EA%B3%BC%EC%99%B8/'
function Recv($ws,[int]$want){$buf=New-Object byte[] 1048576;while($true){$seg=[ArraySegment[byte]]::new($buf);$ms=New-Object IO.MemoryStream;do{$r=$ws.ReceiveAsync($seg,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$ms.Write($buf,0,$r.Count)}while(-not $r.EndOfMessage);$j=[Text.Encoding]::UTF8.GetString($ms.ToArray())|ConvertFrom-Json;if($null -ne $j.id -and [int]$j.id -eq $want){return $j}}}
function Cmd($ws,[ref]$n,[string]$method,$params){$id=$n.Value;$n.Value++;$s=@{id=$id;method=$method;params=$params}|ConvertTo-Json -Compress -Depth 10;$b=[Text.Encoding]::UTF8.GetBytes($s);$ws.SendAsync([ArraySegment[byte]]::new($b),[Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult()|Out-Null;Recv $ws $id}
$profile=Join-Path $env:TEMP 'studyway-heading-alignment-9410';if(Test-Path $profile){Remove-Item $profile -Recurse -Force};$url="http://127.0.0.1:8905$page";$proc=Start-Process $Chrome -ArgumentList @('--headless=new','--remote-debugging-port=9410',"--user-data-dir=$profile",'--no-first-run','--disable-gpu','--hide-scrollbars',$url) -WindowStyle Hidden -PassThru
try{$targets=$null;for($i=0;$i-lt50-and$null-eq$targets;$i++){Start-Sleep -Milliseconds 200;try{$targets=Invoke-RestMethod 'http://127.0.0.1:9410/json'}catch{}};$target=$targets|Where-Object{$_.type-eq'page'-and$_.url-like"*$page*"}|Select-Object -First 1;$ws=[Net.WebSockets.ClientWebSocket]::new();$ws.ConnectAsync([Uri]$target.webSocketDebuggerUrl,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$n=1;Cmd $ws ([ref]$n) 'Page.enable' @{}|Out-Null;$rows=@();foreach($width in @(320,360,375,390,412,430,504)){Cmd $ws ([ref]$n) 'Emulation.setDeviceMetricsOverride' @{width=$width;height=1400;deviceScaleFactor=1;mobile=$true;screenWidth=$width;screenHeight=1400}|Out-Null;Cmd $ws ([ref]$n) 'Page.reload' @{ignoreCache=$true}|Out-Null;Start-Sleep -Milliseconds 800;$expr=@'
(()=>{const box=document.querySelector('.content-heading-card'),img=document.querySelector('.content-image-sequence img'),h1=document.querySelector('h1'),article=document.querySelector('.content-body-card'),br=document.querySelector('.breadcrumbs'),b=box.getBoundingClientRect(),i=img.getBoundingClientRect(),h=h1.getBoundingClientRect(),a=article.getBoundingClientRect(),r=br.getBoundingClientRect(),bs=getComputedStyle(box);return{viewport:innerWidth,headingWidth:b.width,headingLeft:b.left,headingRight:b.right,headingPaddingLeft:parseFloat(bs.paddingLeft),headingPaddingRight:parseFloat(bs.paddingRight),imageWidth:i.width,imageLeft:i.left,imageRight:i.right,h1Width:h.width,h1Left:h.left,h1Right:h.right,bodyWidth:a.width,bodyLeft:a.left,bodyRight:a.right,breadcrumbWidth:r.width,breadcrumbLeft:r.left,breadcrumbRight:r.right,horizontalOverflow:Math.max(0,document.documentElement.scrollWidth-innerWidth),crop:Math.abs((img.naturalWidth/img.naturalHeight)-(i.width/i.height))}})()
'@;$e=Cmd $ws ([ref]$n) 'Runtime.evaluate' @{expression=$expr;returnByValue=$true};$s=Cmd $ws ([ref]$n) 'Page.captureScreenshot' @{format='png';fromSurface=$true;captureBeyondViewport=$false};[IO.File]::WriteAllBytes((Join-Path $shots "heading-$width.png"),[Convert]::FromBase64String($s.result.data));$rows+=$e.result.result.value};$ws.Dispose();$clean=@($rows|Where-Object{$null-ne$_.viewport});$clean|ConvertTo-Json -Depth 6|Set-Content (Join-Path $report 'chrome-heading-alignment.json') -Encoding UTF8;$clean|ConvertTo-Json -Depth 6}finally{if(-not$proc.HasExited){Stop-Process $proc.Id -Force}}
