param([string]$Chrome='C:\Program Files\Google\Chrome\Application\chrome.exe')
$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;$out=Join-Path $root 'reports\review-pilot-responsive';New-Item -ItemType Directory -Force $out|Out-Null
function Recv($ws,[int]$want){$buf=New-Object byte[] 1048576;while($true){$seg=[ArraySegment[byte]]::new($buf);$ms=New-Object IO.MemoryStream;do{$r=$ws.ReceiveAsync($seg,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$ms.Write($buf,0,$r.Count)}while(-not $r.EndOfMessage);$j=[Text.Encoding]::UTF8.GetString($ms.ToArray())|ConvertFrom-Json;if($null -ne $j.id -and [int]$j.id -eq $want){return $j}}}
function Cmd($ws,[ref]$n,[string]$method,$params){$id=$n.Value;$n.Value++;$s=@{id=$id;method=$method;params=$params}|ConvertTo-Json -Compress -Depth 10;$b=[Text.Encoding]::UTF8.GetBytes($s);$ws.SendAsync([ArraySegment[byte]]::new($b),[Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult()|Out-Null;Recv $ws $id}
$paths=@('/region/%EA%B0%95%EB%82%A8%EA%B5%AC/all/%EA%B3%BC%EC%99%B8/','/region/%EC%98%81%ED%86%B5%EA%B5%AC-%EC%98%81%ED%86%B5%EB%8F%99/%EA%B3%A02%EC%88%98%ED%95%99%EA%B3%BC%EC%99%B8/','/school/410041504-%EC%B2%AD%EB%AA%85%EA%B3%A0%EB%93%B1%ED%95%99%EA%B5%90/%EA%B3%BC%EC%99%B8/','/school/410041107-%EA%B0%80%ED%8F%89%EA%B3%A0%EB%93%B1%ED%95%99%EA%B5%90/%EA%B3%A03%EC%98%81%EC%96%B4%EA%B3%BC%EC%99%B8/')
$profile=Join-Path $env:TEMP 'studyway-review-pilot-9412';if(Test-Path $profile){Remove-Item $profile -Recurse -Force};$proc=Start-Process $Chrome -ArgumentList @('--headless=new','--remote-debugging-port=9412',"--user-data-dir=$profile",'--no-first-run','--disable-gpu','--hide-scrollbars','http://127.0.0.1:8911/') -WindowStyle Hidden -PassThru
try{$targets=$null;for($i=0;$i-lt50-and$null-eq$targets;$i++){Start-Sleep -Milliseconds 200;try{$targets=Invoke-RestMethod 'http://127.0.0.1:9412/json'}catch{}};$target=$targets|Where-Object{$_.type-eq'page'}|Select-Object -First 1;$ws=[Net.WebSockets.ClientWebSocket]::new();$ws.ConnectAsync([Uri]$target.webSocketDebuggerUrl,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$n=1;Cmd $ws ([ref]$n) 'Page.enable' @{}|Out-Null;$rows=@()
foreach($width in @(320,360,375,390,412,430,1440,1920)){Cmd $ws ([ref]$n) 'Emulation.setDeviceMetricsOverride' @{width=$width;height=1000;deviceScaleFactor=1;mobile=($width-lt768);screenWidth=$width;screenHeight=1000}|Out-Null;Cmd $ws ([ref]$n) 'Page.navigate' @{url=('http://127.0.0.1:8911'+$paths[1])}|Out-Null;Start-Sleep -Milliseconds 800;Cmd $ws ([ref]$n) 'Runtime.evaluate' @{expression="document.querySelector('.learning-case-section').scrollIntoView()"}|Out-Null;Start-Sleep -Milliseconds 200;$e=Cmd $ws ([ref]$n) 'Runtime.evaluate' @{expression="(()=>{const s=document.querySelector('.learning-case-section'),cs=[...document.querySelectorAll('.learning-case-card')];return{viewport:innerWidth,cards:cs.length,columns:getComputedStyle(document.querySelector('.learning-case-grid')).gridTemplateColumns.split(' ').length,overflow:Math.max(0,document.documentElement.scrollWidth-innerWidth),cardOverflow:cs.filter(x=>x.scrollWidth>x.clientWidth||x.scrollHeight>x.clientHeight).length,stars:document.querySelectorAll('.learning-case-stars').length,sectionWidth:s.getBoundingClientRect().width}})()";returnByValue=$true};$rows+=$e.result.result.value;$shot=Cmd $ws ([ref]$n) 'Page.captureScreenshot' @{format='png';fromSurface=$true;captureBeyondViewport=$false};[IO.File]::WriteAllBytes((Join-Path $out "review-$width.png"),[Convert]::FromBase64String($shot.result.data))}
foreach($path in $paths){Cmd $ws ([ref]$n) 'Emulation.setDeviceMetricsOverride' @{width=390;height=1000;deviceScaleFactor=1;mobile=$true;screenWidth=390;screenHeight=1000}|Out-Null;Cmd $ws ([ref]$n) 'Page.navigate' @{url=('http://127.0.0.1:8911'+$path)}|Out-Null;Start-Sleep -Milliseconds 700;Cmd $ws ([ref]$n) 'Runtime.evaluate' @{expression="document.querySelector('.learning-case-section').scrollIntoView()"}|Out-Null;$name=[Math]::Abs($path.GetHashCode());$shot=Cmd $ws ([ref]$n) 'Page.captureScreenshot' @{format='png';fromSurface=$true;captureBeyondViewport=$false};[IO.File]::WriteAllBytes((Join-Path $out "page-$name-390.png"),[Convert]::FromBase64String($shot.result.data))}
$rows|ConvertTo-Json -Depth 5|Set-Content (Join-Path $out 'chrome-responsive.json') -Encoding UTF8;$rows|ConvertTo-Json -Depth 5;$ws.Dispose()}finally{if($proc-and-not$proc.HasExited){Stop-Process $proc.Id -Force}}
