param([string]$Chrome='C:\Program Files\Google\Chrome\Application\chrome.exe')
$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;$report=Join-Path $root 'reports\images-mobile-dom-full-bleed-aligned-cards';$shots=Join-Path $report 'page-screenshots';New-Item -ItemType Directory -Force $shots|Out-Null
$pages=[ordered]@{
  'gangdong'='/region/%EA%B0%95%EB%8F%99%EA%B5%AC/all/%EA%B3%BC%EC%99%B8/'
  'gangbuk'='/region/%EA%B0%95%EB%B6%81%EA%B5%AC/all/%EA%B3%BC%EC%99%B8/'
  'gwanak'='/region/%EA%B4%80%EC%95%85%EA%B5%AC/all/%EA%B3%BC%EC%99%B8/'
  'cheongmyeong-school'='/school/410041504-%EC%B2%AD%EB%AA%85%EA%B3%A0%EB%93%B1%ED%95%99%EA%B5%90/%EA%B3%BC%EC%99%B8/'
}
function Recv($ws,[int]$want){$buf=New-Object byte[] 1048576;while($true){$seg=[ArraySegment[byte]]::new($buf);$ms=New-Object IO.MemoryStream;do{$r=$ws.ReceiveAsync($seg,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$ms.Write($buf,0,$r.Count)}while(-not $r.EndOfMessage);$j=[Text.Encoding]::UTF8.GetString($ms.ToArray())|ConvertFrom-Json;if($null -ne $j.id -and [int]$j.id -eq $want){return $j}}}
function Cmd($ws,[ref]$n,[string]$method,$params){$id=$n.Value;$n.Value++;$s=@{id=$id;method=$method;params=$params}|ConvertTo-Json -Compress -Depth 10;$b=[Text.Encoding]::UTF8.GetBytes($s);$ws.SendAsync([ArraySegment[byte]]::new($b),[Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult()|Out-Null;Recv $ws $id}
$profile=Join-Path $env:TEMP 'studyway-aligned-pages-9440';if(Test-Path $profile){Remove-Item $profile -Recurse -Force};$proc=Start-Process $Chrome -ArgumentList @('--headless=new','--remote-debugging-port=9440',"--user-data-dir=$profile",'--no-first-run','--disable-gpu','--hide-scrollbars','http://127.0.0.1:8906/') -WindowStyle Hidden -PassThru
try{$targets=$null;for($i=0;$i-lt50-and$null-eq$targets;$i++){Start-Sleep -Milliseconds 200;try{$targets=Invoke-RestMethod 'http://127.0.0.1:9440/json'}catch{}};$t=$targets|Where-Object{$_.type-eq'page'}|Select-Object -First 1;$ws=[Net.WebSockets.ClientWebSocket]::new();$ws.ConnectAsync([Uri]$t.webSocketDebuggerUrl,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$n=1;Cmd $ws ([ref]$n) 'Page.enable' @{}|Out-Null;Cmd $ws ([ref]$n) 'Emulation.setDeviceMetricsOverride' @{width=390;height=1400;deviceScaleFactor=1;mobile=$true;screenWidth=390;screenHeight=1400}|Out-Null;$rows=@();foreach($entry in $pages.GetEnumerator()){Cmd $ws ([ref]$n) 'Page.navigate' @{url="http://127.0.0.1:8906$($entry.Value)"}|Out-Null;Start-Sleep -Milliseconds 900;$expr="(()=>{const b=document.querySelector('.content-heading-card').getBoundingClientRect(),i=document.querySelector('.content-image-sequence img').getBoundingClientRect(),a=document.querySelector('.content-body-card').getBoundingClientRect();return{title:document.querySelector('h1').textContent,heading:[b.left,b.right,b.width],image:[i.left,i.right,i.width],body:[a.left,a.right,a.width],overflow:Math.max(0,document.documentElement.scrollWidth-innerWidth)}})()";$e=Cmd $ws ([ref]$n) 'Runtime.evaluate' @{expression=$expr;returnByValue=$true};$s=Cmd $ws ([ref]$n) 'Page.captureScreenshot' @{format='png';fromSurface=$true;captureBeyondViewport=$false};[IO.File]::WriteAllBytes((Join-Path $shots "$($entry.Key)-390.png"),[Convert]::FromBase64String($s.result.data));Cmd $ws ([ref]$n) 'Runtime.evaluate' @{expression="document.querySelector('.content-body-card').scrollIntoView({block:'start'});window.scrollBy(0,-220)"}|Out-Null;Start-Sleep -Milliseconds 300;$bottom=Cmd $ws ([ref]$n) 'Page.captureScreenshot' @{format='png';fromSurface=$true;captureBeyondViewport=$false};[IO.File]::WriteAllBytes((Join-Path $shots "$($entry.Key)-body-boundary-390.png"),[Convert]::FromBase64String($bottom.result.data));$rows+=[pscustomobject]@{page=$entry.Key;metrics=$e.result.result.value}};$ws.Dispose();$clean=@($rows|Where-Object{$null-ne$_.page});$clean|ConvertTo-Json -Depth 6|Set-Content (Join-Path $report 'chrome-page-visual-audit.json') -Encoding UTF8;$clean|ConvertTo-Json -Depth 6}finally{if(-not$proc.HasExited){Stop-Process $proc.Id -Force}}
