param([string]$Chrome='C:\Program Files\Google\Chrome\Application\chrome.exe')
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot
$out=Join-Path $root 'reports\images-mobile-full-bleed\real-window-diagnostics'
New-Item -ItemType Directory -Force -Path $out|Out-Null
$page='/school/110041107-%EA%B2%BD%EB%8F%99%EA%B3%A0%EB%93%B1%ED%95%99%EA%B5%90/%EC%98%81%EC%96%B4%EA%B3%BC%EC%99%B8/'
function Recv($ws,[int]$want){$buf=New-Object byte[] 1048576;while($true){$seg=[ArraySegment[byte]]::new($buf);$ms=New-Object IO.MemoryStream;do{$r=$ws.ReceiveAsync($seg,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$ms.Write($buf,0,$r.Count)}while(-not $r.EndOfMessage);$j=[Text.Encoding]::UTF8.GetString($ms.ToArray())|ConvertFrom-Json;if($null-ne $j.id-and[int]$j.id-eq$want){return $j}}}
function Cmd($ws,[ref]$n,[string]$method,$params){$id=$n.Value;$n.Value++;$s=@{id=$id;method=$method;params=$params}|ConvertTo-Json -Compress -Depth 12;$b=[Text.Encoding]::UTF8.GetBytes($s);$ws.SendAsync([ArraySegment[byte]]::new($b),[Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult()|Out-Null;Recv $ws $id}
function One([int]$requested,[int]$debug){$profile=Join-Path $env:TEMP "studyway-real-window-$debug";if(Test-Path $profile){Remove-Item $profile -Recurse -Force};$url="http://127.0.0.1:8902$page";$p=Start-Process $Chrome -ArgumentList @('--headless=new',"--remote-debugging-port=$debug","--user-data-dir=$profile",'--no-first-run','--disable-gpu','--hide-scrollbars',"--window-size=$requested,1400",$url) -WindowStyle Hidden -PassThru;try{$ts=$null;for($i=0;$i-lt50-and$null-eq$ts;$i++){Start-Sleep -Milliseconds 200;try{$ts=Invoke-RestMethod "http://127.0.0.1:$debug/json"}catch{}};$t=$ts|Where-Object{$_.type-eq'page'-and$_.url-like"*$page*"}|Select-Object -First 1;$ws=[Net.WebSockets.ClientWebSocket]::new();$ws.ConnectAsync([Uri]$t.webSocketDebuggerUrl,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$n=1;Cmd $ws ([ref]$n) 'Page.enable' @{}|Out-Null;Start-Sleep -Milliseconds 600;$expr=@'
(()=>{const selectors={html:'html',body:'body',main:'main',article:'article',contentWrapper:'article > *',sequence:'.content-image-sequence',img:'.content-image-sequence img'};const read=(el)=>{const r=el.getBoundingClientRect(),s=getComputedStyle(el);return{left:r.left,right:r.right,width:r.width,computedWidth:s.width,maxWidth:s.maxWidth,marginLeft:s.marginLeft,marginRight:s.marginRight,paddingLeft:s.paddingLeft,paddingRight:s.paddingRight,position:s.position,leftStyle:s.left,transform:s.transform,overflow:s.overflow,boxSizing:s.boxSizing}};const elements={};for(const[k,q]of Object.entries(selectors)){const el=document.querySelector(q);elements[k]=el?read(el):null}const img=document.querySelector('.content-image-sequence img'),h1=document.querySelector('h1'),ir=img.getBoundingClientRect(),hr=h1.getBoundingClientRect();return{innerWidth,outerWidth,devicePixelRatio,scrollWidth:document.documentElement.scrollWidth,horizontalOverflow:Math.max(0,document.documentElement.scrollWidth-innerWidth),h1:{left:hr.left,right:hr.right,width:hr.width},image:{left:ir.left,right:ir.right,width:ir.width,naturalWidth:img.naturalWidth,naturalHeight:img.naturalHeight},elements}})()
'@;$e=Cmd $ws ([ref]$n) 'Runtime.evaluate' @{expression=$expr;returnByValue=$true};$shot=Cmd $ws ([ref]$n) 'Page.captureScreenshot' @{format='png';fromSurface=$true;captureBeyondViewport=$false};[IO.File]::WriteAllBytes((Join-Path $out "real-window-requested-$requested.png"),[Convert]::FromBase64String($shot.result.data));$ws.Dispose();[ordered]@{requestedWindowWidth=$requested;metrics=$e.result.result.value}}finally{if(-not$p.HasExited){Stop-Process $p.Id -Force}}}
$rows=@();$i=0;foreach($w in @(320,360,375,390,412,430)){$rows+=One $w (9250+$i);$i++};$rows|ConvertTo-Json -Depth 12|Set-Content (Join-Path $out 'diagnostics.json') -Encoding UTF8;$rows|ConvertTo-Json -Depth 12
