param([string]$Chrome='C:\Program Files\Google\Chrome\Application\chrome.exe',[int]$Port=8780)
$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;$out=Join-Path $root 'reports\search-meta-final\chrome';New-Item -ItemType Directory -Force $out|Out-Null
function Recv($w,[int]$want){$b=New-Object byte[] 1048576;while($true){$s=[ArraySegment[byte]]::new($b);$m=New-Object IO.MemoryStream;do{$r=$w.ReceiveAsync($s,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$m.Write($b,0,$r.Count)}while(-not$r.EndOfMessage);$j=[Text.Encoding]::UTF8.GetString($m.ToArray())|ConvertFrom-Json;if($null-ne$j.id-and[int]$j.id-eq$want){return $j}}}
function Cmd($w,[ref]$n,[string]$method,$params){$id=$n.Value;$n.Value++;$j=@{id=$id;method=$method;params=$params}|ConvertTo-Json -Compress -Depth 10;$b=[Text.Encoding]::UTF8.GetBytes($j);$w.SendAsync([ArraySegment[byte]]::new($b),[Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult()|Out-Null;Recv $w $id}
$pages=Get-Content (Join-Path $root 'reports\search-meta-final\representative-20.json') -Raw -Encoding UTF8|ConvertFrom-Json
$profile=Join-Path $env:TEMP 'studyway-search-meta-9438';if(Test-Path $profile){Remove-Item $profile -Recurse -Force};$proc=Start-Process $Chrome -ArgumentList @('--headless=new','--remote-debugging-port=9438',"--user-data-dir=$profile",'--no-first-run','--disable-gpu',"http://127.0.0.1:$Port/") -WindowStyle Hidden -PassThru
try{$targets=$null;for($i=0;$i-lt50-and$null-eq$targets;$i++){Start-Sleep -Milliseconds 200;try{$targets=Invoke-RestMethod 'http://127.0.0.1:9438/json'}catch{}};$t=$targets|Where-Object{$_.type-eq'page'}|Select-Object -First 1;$w=[Net.WebSockets.ClientWebSocket]::new();$w.ConnectAsync([Uri]$t.webSocketDebuggerUrl,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$n=1;Cmd $w ([ref]$n) 'Page.enable' @{}|Out-Null
$expr=@'
(()=>{const one=s=>{const x=[...document.querySelectorAll(s)];return{count:x.length,value:x[0]?.content||x[0]?.href||x[0]?.textContent||''}},m={title:one('title'),description:one('meta[name="description"]'),canonical:one('link[rel="canonical"]'),ogTitle:one('meta[property="og:title"]'),ogDescription:one('meta[property="og:description"]'),ogUrl:one('meta[property="og:url"]'),ogType:one('meta[property="og:type"]'),ogImage:one('meta[property="og:image"]'),twitterCard:one('meta[name="twitter:card"]'),twitterTitle:one('meta[name="twitter:title"]'),twitterDescription:one('meta[name="twitter:description"]'),twitterImage:one('meta[name="twitter:image"]')};return{meta:m,pass:Object.values(m).every(x=>x.count===1)&&m.title.value===m.ogTitle.value&&m.description.value===m.ogDescription.value&&m.canonical.value===m.ogUrl.value&&m.ogImage.value===m.twitterImage.value&&!/localhost|127\.0\.0\.1|file:\/\//.test(JSON.stringify(m))}})()
'@
$results=@();foreach($p in $pages){$http=Invoke-WebRequest -Uri ("http://127.0.0.1:$Port"+$p.url) -UseBasicParsing;Cmd $w ([ref]$n) 'Page.navigate' @{url=("http://127.0.0.1:$Port"+$p.url)}|Out-Null;Start-Sleep -Milliseconds 350;$e=Cmd $w ([ref]$n) 'Runtime.evaluate' @{expression=$expr;returnByValue=$true};$v=$e.result.result.value;$v|Add-Member label $p.label;$v|Add-Member url $p.url;$v|Add-Member http ([int]$http.StatusCode);$results+=$v}
$images=$results|ForEach-Object{$_.meta.ogImage.value}|Sort-Object -Unique;$imageHttp=@();foreach($u in $images){$r=Invoke-WebRequest -Uri $u.Replace('https://studyway.kr',"http://127.0.0.1:$Port") -UseBasicParsing;$imageHttp+=@{url=$u;status=[int]$r.StatusCode}}
$result=@{count=$results.Count;passed=@($results|Where-Object{$_.pass-and$_.http-eq200}).Count;pages=$results;image_http=$imageHttp};$result|ConvertTo-Json -Depth 10|Set-Content (Join-Path $out 'representative-20.json') -Encoding UTF8;$result|ConvertTo-Json -Depth 5;$w.Dispose()}finally{if($proc-and-not$proc.HasExited){Stop-Process $proc.Id -Force}}
