param([string]$Chrome='C:\Program Files\Google\Chrome\Application\chrome.exe',[int]$ExistingPort=8775,[int]$NewPort=8776,[string]$ReportRelative='reports\home-soft-region-colors\chrome')
$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;$out=Join-Path $root $ReportRelative;New-Item -ItemType Directory -Force $out|Out-Null
function Recv($w,[int]$want){$b=New-Object byte[] 1048576;while($true){$s=[ArraySegment[byte]]::new($b);$m=New-Object IO.MemoryStream;do{$r=$w.ReceiveAsync($s,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$m.Write($b,0,$r.Count)}while(-not$r.EndOfMessage);$j=[Text.Encoding]::UTF8.GetString($m.ToArray())|ConvertFrom-Json;if($null-ne$j.id-and[int]$j.id-eq$want){return $j}}}
function Cmd($w,[ref]$n,[string]$method,$params){$id=$n.Value;$n.Value++;$j=@{id=$id;method=$method;params=$params}|ConvertTo-Json -Compress -Depth 10;$b=[Text.Encoding]::UTF8.GetBytes($j);$w.SendAsync([ArraySegment[byte]]::new($b),[Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult()|Out-Null;Recv $w $id}
$profile=Join-Path $env:TEMP 'studyway-soft-colors-9436';if(Test-Path $profile){Remove-Item $profile -Recurse -Force};$proc=Start-Process $Chrome -ArgumentList @('--headless=new','--remote-debugging-port=9436',"--user-data-dir=$profile",'--no-first-run','--disable-gpu','--hide-scrollbars',"http://127.0.0.1:$NewPort/") -WindowStyle Hidden -PassThru
try{$targets=$null;for($i=0;$i-lt50-and$null-eq$targets;$i++){Start-Sleep -Milliseconds 200;try{$targets=Invoke-RestMethod 'http://127.0.0.1:9436/json'}catch{}};$t=$targets|Where-Object{$_.type-eq'page'}|Select-Object -First 1;$w=[Net.WebSockets.ClientWebSocket]::new();$w.ConnectAsync([Uri]$t.webSocketDebuggerUrl,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$n=1;Cmd $w ([ref]$n) 'Page.enable' @{}|Out-Null
$expr=@'
(()=>{const groups=[...document.querySelectorAll('#regions>section')],links=[...document.querySelectorAll('#regions .link-grid a')],g=groups[0].querySelector('.link-grid'),r=links.map(x=>x.getBoundingClientRect()),style=x=>{const c=getComputedStyle(x);return{background:c.backgroundColor,border:c.borderColor,color:c.color,width:c.width,height:c.height,padding:c.padding,fontSize:c.fontSize,borderRadius:c.borderRadius,transition:c.transition,transform:c.transform}},rgb=s=>s.match(/\d+/g).slice(0,3).map(Number),lum=a=>{a=a.map(v=>v/255).map(v=>v<=.03928?v/12.92:((v+.055)/1.055)**2.4);return .2126*a[0]+.7152*a[1]+.0722*a[2]},ratio=(a,b)=>{a=lum(rgb(a));b=lum(rgb(b));return(Math.max(a,b)+.05)/(Math.min(a,b)+.05)};const ss=style(groups[0].querySelector('a')),gs=style(groups[1].querySelector('a'));return{columns:getComputedStyle(g).gridTemplateColumns.split(' ').length,columnGap:getComputedStyle(g).columnGap,rowGap:getComputedStyle(g).rowGap,minHeight:Math.min(...r.map(x=>x.height)),maxHeight:Math.max(...r.map(x=>x.height)),minWidth:Math.min(...r.map(x=>x.width)),textClipped:links.filter(x=>x.scrollWidth>x.clientWidth||x.scrollHeight>x.clientHeight).length,overflow:Math.max(0,document.documentElement.scrollWidth-innerWidth),allVisible:links.every(x=>x.offsetParent!==null),seoul:ss,gyeonggi:gs,seoulContrast:ratio(ss.color,ss.background),gyeonggiContrast:ratio(gs.color,gs.background),h1:document.querySelectorAll('h1').length,hrefs:document.querySelectorAll('a[href]').length}})()
'@
$responsive=@();foreach($width in @(1920,1440,768,430,412,390,375,360,320)){foreach($port in @($ExistingPort,$NewPort)){Cmd $w ([ref]$n) 'Emulation.setDeviceMetricsOverride' @{width=$width;height=900;deviceScaleFactor=1;mobile=($width-lt768);screenWidth=$width;screenHeight=900}|Out-Null;Cmd $w ([ref]$n) 'Page.navigate' @{url=("http://127.0.0.1:$port/")}|Out-Null;Start-Sleep -Milliseconds 550;$e=Cmd $w ([ref]$n) 'Runtime.evaluate' @{expression=$expr;returnByValue=$true};$v=$e.result.result.value;$v|Add-Member width $width;$v|Add-Member port $port;$responsive+=$v;if($width-in@(390,430,1440)){Cmd $w ([ref]$n) 'Runtime.evaluate' @{expression="document.querySelector('#regions').scrollIntoView()"}|Out-Null;Start-Sleep -Milliseconds 100;$shot=Cmd $w ([ref]$n) 'Page.captureScreenshot' @{format='png';fromSurface=$true;captureBeyondViewport=$false};[IO.File]::WriteAllBytes((Join-Path $out "regions-$width-$port.png"),[Convert]::FromBase64String($shot.result.data))}}}
Cmd $w ([ref]$n) 'Emulation.setDeviceMetricsOverride' @{width=1440;height=900;deviceScaleFactor=1;mobile=$false;screenWidth=1440;screenHeight=900}|Out-Null;Cmd $w ([ref]$n) 'Page.navigate' @{url=("http://127.0.0.1:$NewPort/")}|Out-Null;Start-Sleep -Milliseconds 500
$hover=@{};foreach($group in @(1,2)){$coord=Cmd $w ([ref]$n) 'Runtime.evaluate' @{expression="(()=>{const r=document.querySelector('#regions>section:nth-of-type($group) a').getBoundingClientRect();scrollTo(0,r.top+scrollY-300);return{x:r.left+r.width/2,y:300+r.height/2}})()";returnByValue=$true};Cmd $w ([ref]$n) 'Input.dispatchMouseEvent' @{type='mouseMoved';x=$coord.result.result.value.x;y=$coord.result.result.value.y}|Out-Null;Start-Sleep -Milliseconds 250;$e=Cmd $w ([ref]$n) 'Runtime.evaluate' @{expression="(()=>{const c=getComputedStyle(document.querySelector('#regions>section:nth-of-type($group) a'));return{background:c.backgroundColor,border:c.borderColor,transform:c.transform}})()";returnByValue=$true};$hover["$group"]=$e.result.result.value}
$result=@{responsive=$responsive;hover=$hover};$result|ConvertTo-Json -Depth 8|Set-Content (Join-Path $out 'validation.json') -Encoding UTF8;$result|ConvertTo-Json -Depth 5;$w.Dispose()}finally{if($proc-and-not$proc.HasExited){Stop-Process $proc.Id -Force}}
