param([string]$Chrome='C:\Program Files\Google\Chrome\Application\chrome.exe',[int]$Port=8778,[string]$ReportRelative='reports\mobile-contact-cta\chrome')
$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;$out=Join-Path $root $ReportRelative;New-Item -ItemType Directory -Force $out|Out-Null
function Recv($w,[int]$want){$b=New-Object byte[] 1048576;while($true){$s=[ArraySegment[byte]]::new($b);$m=New-Object IO.MemoryStream;do{$r=$w.ReceiveAsync($s,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$m.Write($b,0,$r.Count)}while(-not$r.EndOfMessage);$j=[Text.Encoding]::UTF8.GetString($m.ToArray())|ConvertFrom-Json;if($null-ne$j.id-and[int]$j.id-eq$want){return $j}}}
function Cmd($w,[ref]$n,[string]$method,$params){$id=$n.Value;$n.Value++;$j=@{id=$id;method=$method;params=$params}|ConvertTo-Json -Compress -Depth 10;$b=[Text.Encoding]::UTF8.GetBytes($j);$w.SendAsync([ArraySegment[byte]]::new($b),[Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult()|Out-Null;Recv $w $id}
$pages=@(
 @{name='home';url='/'},
 @{name='region-general';url='/region/%EA%B0%95%EB%82%A8%EA%B5%AC/all/%EA%B3%BC%EC%99%B8/'},
 @{name='region-math';url='/region/%EC%98%81%ED%86%B5%EA%B5%AC-%EC%98%81%ED%86%B5%EB%8F%99/%EA%B3%A02%EC%88%98%ED%95%99%EA%B3%BC%EC%99%B8/'},
 @{name='region-english';url='/region/%EA%B5%AC%EB%A1%9C%EA%B5%AC-%EA%B0%9C%EB%B4%89%EB%8F%99/%EA%B3%A01%EC%98%81%EC%96%B4%EA%B3%BC%EC%99%B8/'},
 @{name='school-general';url='/school/410041504-%EC%B2%AD%EB%AA%85%EA%B3%A0%EB%93%B1%ED%95%99%EA%B5%90/%EA%B3%BC%EC%99%B8/'},
 @{name='school-math';url='/school/110041101-%EA%B0%80%EB%9D%BD%EA%B3%A0%EB%93%B1%ED%95%99%EA%B5%90/%EA%B3%A02%EC%88%98%ED%95%99%EA%B3%BC%EC%99%B8/'},
 @{name='school-english';url='/school/110041101-%EA%B0%80%EB%9D%BD%EA%B3%A0%EB%93%B1%ED%95%99%EA%B5%90/%EA%B3%A03%EC%98%81%EC%96%B4%EA%B3%BC%EC%99%B8/'}
)
$http=@();foreach($p in $pages){try{$r=Invoke-WebRequest -Uri ("http://127.0.0.1:$Port"+$p.url) -UseBasicParsing;$http+=@{name=$p.name;url=$p.url;status=[int]$r.StatusCode}}catch{$http+=@{name=$p.name;url=$p.url;status=0}}}
$profile=Join-Path $env:TEMP 'studyway-mobile-cta-9437';if(Test-Path $profile){Remove-Item $profile -Recurse -Force};$proc=Start-Process $Chrome -ArgumentList @('--headless=new','--remote-debugging-port=9437',"--user-data-dir=$profile",'--no-first-run','--disable-gpu','--hide-scrollbars',"http://127.0.0.1:$Port/") -WindowStyle Hidden -PassThru
try{$targets=$null;for($i=0;$i-lt50-and$null-eq$targets;$i++){Start-Sleep -Milliseconds 200;try{$targets=Invoke-RestMethod 'http://127.0.0.1:9437/json'}catch{}};$t=$targets|Where-Object{$_.type-eq'page'}|Select-Object -First 1;$w=[Net.WebSockets.ClientWebSocket]::new();$w.ConnectAsync([Uri]$t.webSocketDebuggerUrl,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$n=1;Cmd $w ([ref]$n) 'Page.enable' @{}|Out-Null
$expr=@'
(()=>{const c=document.querySelector('.mobile-contact-cta'),a=[...c.querySelectorAll('a')],r=c.getBoundingClientRect(),s=getComputedStyle(c),ar=a.map(x=>x.getBoundingClientRect()),as=a.map(x=>getComputedStyle(x)),nums=[...c.querySelectorAll('small')],icons=[...c.querySelectorAll('.mobile-contact-cta__icon')],strong=c.querySelector('strong'),outside=x=>{const n=x.getBoundingClientRect(),p=x.closest('a').getBoundingClientRect();return n.left<p.left||n.right>p.right||n.top<p.top||n.bottom>p.bottom};return{wrappers:document.querySelectorAll('.mobile-contact-cta').length,tel:document.querySelectorAll('.mobile-contact-cta a[href="tel:01049479030"]').length,sms:document.querySelectorAll('.mobile-contact-cta a[href="sms:01049479030"]').length,telHref:a[0].getAttribute('href'),smsHref:a[1].getAttribute('href'),display:s.display,position:s.position,height:r.height,width:r.width,bottom:s.bottom,zIndex:s.zIndex,visible:r.width>0&&r.height>0&&s.display!=='none',linkHeights:ar.map(x=>x.height),nowrap:nums.every(x=>getComputedStyle(x).whiteSpace==='nowrap'),oneLine:a.every(x=>x.scrollHeight<=x.clientHeight&&x.scrollWidth<=x.clientWidth),numberCount:nums.length,numberClipped:nums.filter(outside).length,iconCount:icons.length,iconClipped:icons.filter(outside).length,titleFont:strong?getComputedStyle(strong).fontSize:null,numberFont:nums[0]?getComputedStyle(nums[0]).fontSize:null,iconSize:icons[0]?icons[0].getBoundingClientRect().width:null,callBackground:getComputedStyle(a[0]).backgroundColor,smsBackground:getComputedStyle(a[1]).backgroundColor,border:s.border,radius:s.borderRadius,shadow:s.boxShadow,overflow:Math.max(0,document.documentElement.scrollWidth-innerWidth),bodyPaddingBottom:getComputedStyle(document.body).paddingBottom}})()
'@
$responsive=@();foreach($width in @(320,360,375,390,412,430,768,1440,1920)){Cmd $w ([ref]$n) 'Emulation.setDeviceMetricsOverride' @{width=$width;height=900;deviceScaleFactor=1;mobile=($width-lt768);screenWidth=$width;screenHeight=900}|Out-Null;Cmd $w ([ref]$n) 'Page.navigate' @{url=("http://127.0.0.1:$Port/")}|Out-Null;Start-Sleep -Milliseconds 550;$e=Cmd $w ([ref]$n) 'Runtime.evaluate' @{expression=$expr;returnByValue=$true};$v=$e.result.result.value;$v|Add-Member viewportWidth $width;$responsive+=$v}
$representatives=@();foreach($p in $pages){Cmd $w ([ref]$n) 'Emulation.setDeviceMetricsOverride' @{width=390;height=900;deviceScaleFactor=1;mobile=$true;screenWidth=390;screenHeight=900}|Out-Null;Cmd $w ([ref]$n) 'Page.navigate' @{url=("http://127.0.0.1:$Port"+$p.url)}|Out-Null;Start-Sleep -Milliseconds 500;$e=Cmd $w ([ref]$n) 'Runtime.evaluate' @{expression=$expr;returnByValue=$true};$v=$e.result.result.value;$v|Add-Member name $p.name;$representatives+=$v}
$contentUrl=$pages[1].url;$bottomMetrics=@();foreach($width in @(390,430)){Cmd $w ([ref]$n) 'Emulation.setDeviceMetricsOverride' @{width=$width;height=900;deviceScaleFactor=1;mobile=$true;screenWidth=$width;screenHeight=900}|Out-Null;Cmd $w ([ref]$n) 'Page.navigate' @{url=("http://127.0.0.1:$Port/")}|Out-Null;Start-Sleep -Milliseconds 500;$full=Cmd $w ([ref]$n) 'Page.captureScreenshot' @{format='png';fromSurface=$true;captureBeyondViewport=$true};[IO.File]::WriteAllBytes((Join-Path $out "home-full-$width.png"),[Convert]::FromBase64String($full.result.data));Cmd $w ([ref]$n) 'Page.navigate' @{url=("http://127.0.0.1:$Port"+$contentUrl)}|Out-Null;Start-Sleep -Milliseconds 500;Cmd $w ([ref]$n) 'Runtime.evaluate' @{expression='scrollTo(0,document.documentElement.scrollHeight*.48)'}|Out-Null;Start-Sleep -Milliseconds 150;$mid=Cmd $w ([ref]$n) 'Page.captureScreenshot' @{format='png';fromSurface=$true;captureBeyondViewport=$false};[IO.File]::WriteAllBytes((Join-Path $out "content-middle-$width.png"),[Convert]::FromBase64String($mid.result.data));Cmd $w ([ref]$n) 'Runtime.evaluate' @{expression='scrollTo(0,document.documentElement.scrollHeight)'}|Out-Null;Start-Sleep -Milliseconds 200;$bottomExpr="(()=>{const c=document.querySelector('.mobile-contact-cta').getBoundingClientRect(),f=document.querySelector('footer').getBoundingClientRect();return{ctaTop:c.top,footerBottom:f.bottom,gap:c.top-f.bottom,scrollY,scrollHeight:document.documentElement.scrollHeight}})()";$e=Cmd $w ([ref]$n) 'Runtime.evaluate' @{expression=$bottomExpr;returnByValue=$true};$bottom=$e.result.result.value;$bottom|Add-Member width $width;$bottomMetrics+=$bottom;$shot=Cmd $w ([ref]$n) 'Page.captureScreenshot' @{format='png';fromSurface=$true;captureBeyondViewport=$false};[IO.File]::WriteAllBytes((Join-Path $out "content-bottom-$width.png"),[Convert]::FromBase64String($shot.result.data))}
$result=@{http=$http;responsive=$responsive;representatives=$representatives;bottom=$bottomMetrics};$result|ConvertTo-Json -Depth 8|Set-Content (Join-Path $out 'validation.json') -Encoding UTF8;$result|ConvertTo-Json -Depth 5;$w.Dispose()}finally{if($proc-and-not$proc.HasExited){Stop-Process $proc.Id -Force}}
