param([string]$Chrome='C:\Program Files\Google\Chrome\Application\chrome.exe')
$ErrorActionPreference='Stop'
$root=Split-Path -Parent $PSScriptRoot;$out=Join-Path $root 'reports\home-compact-regions\chrome';New-Item -ItemType Directory -Force $out|Out-Null
function Recv($ws,[int]$want){$buf=New-Object byte[] 1048576;while($true){$seg=[ArraySegment[byte]]::new($buf);$ms=New-Object IO.MemoryStream;do{$r=$ws.ReceiveAsync($seg,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$ms.Write($buf,0,$r.Count)}while(-not$r.EndOfMessage);$j=[Text.Encoding]::UTF8.GetString($ms.ToArray())|ConvertFrom-Json;if($null-ne$j.id-and[int]$j.id-eq$want){return $j}}}
function Cmd($ws,[ref]$n,[string]$method,$params){$id=$n.Value;$n.Value++;$s=@{id=$id;method=$method;params=$params}|ConvertTo-Json -Compress -Depth 12;$b=[Text.Encoding]::UTF8.GetBytes($s);$ws.SendAsync([ArraySegment[byte]]::new($b),[Net.WebSockets.WebSocketMessageType]::Text,$true,[Threading.CancellationToken]::None).GetAwaiter().GetResult()|Out-Null;Recv $ws $id}
$profile=Join-Path $env:TEMP 'studyway-compact-regions-9435';if(Test-Path $profile){Remove-Item $profile -Recurse -Force}
$proc=Start-Process $Chrome -ArgumentList @('--headless=new','--remote-debugging-port=9435',"--user-data-dir=$profile",'--no-first-run','--disable-gpu','--hide-scrollbars','http://127.0.0.1:8775/') -WindowStyle Hidden -PassThru
try{
 $targets=$null;for($i=0;$i-lt50-and$null-eq$targets;$i++){Start-Sleep -Milliseconds 200;try{$targets=Invoke-RestMethod 'http://127.0.0.1:9435/json'}catch{}}
 $target=$targets|Where-Object{$_.type-eq'page'}|Select-Object -First 1;$ws=[Net.WebSockets.ClientWebSocket]::new();$ws.ConnectAsync([Uri]$target.webSocketDebuggerUrl,[Threading.CancellationToken]::None).GetAwaiter().GetResult();$n=1;Cmd $ws ([ref]$n) 'Page.enable' @{}|Out-Null
 $expr=@'
(()=>{const r=document.querySelector('#regions'),g=r.querySelector('.link-grid'),links=[...r.querySelectorAll('.link-grid a')],rects=links.map(x=>x.getBoundingClientRect()),cs=getComputedStyle(links[0]);return{regionHeight:r.getBoundingClientRect().height,scrollHeight:document.documentElement.scrollHeight,columns:getComputedStyle(g).gridTemplateColumns.split(' ').length,buttonMinHeight:Math.min(...rects.map(x=>x.height)),buttonMaxHeight:Math.max(...rects.map(x=>x.height)),buttonMinWidth:Math.min(...rects.map(x=>x.width)),fontSize:cs.fontSize,columnGap:getComputedStyle(g).columnGap,rowGap:getComputedStyle(g).rowGap,textClipped:links.filter(x=>x.scrollWidth>x.clientWidth||x.scrollHeight>x.clientHeight).length,overlap:rects.some((a,i)=>rects.some((b,j)=>j>i&&!(a.right<=b.left||b.right<=a.left||a.bottom<=b.top||b.bottom<=a.top))),overflow:Math.max(0,document.documentElement.scrollWidth-innerWidth),seoul:r.querySelectorAll(':scope>section:nth-of-type(1) .link-grid a').length,gyeonggi:r.querySelectorAll(':scope>section:nth-of-type(2) .link-grid a').length,allVisible:links.every(x=>x.offsetParent!==null&&x.getBoundingClientRect().height>0),hrefs:links.map(x=>x.getAttribute('href'))}})()
'@
 $responsive=@();$heights=@()
 foreach($width in @(1920,1440,768,430,412,390,375,360,320)){
  foreach($port in @(8774,8775)){
   Cmd $ws ([ref]$n) 'Emulation.setDeviceMetricsOverride' @{width=$width;height=900;deviceScaleFactor=1;mobile=($width-lt768);screenWidth=$width;screenHeight=900}|Out-Null
   Cmd $ws ([ref]$n) 'Page.navigate' @{url=("http://127.0.0.1:$port/")}|Out-Null;Start-Sleep -Milliseconds 600
   $e=Cmd $ws ([ref]$n) 'Runtime.evaluate' @{expression=$expr;returnByValue=$true};$v=$e.result.result.value;$v|Add-Member width $width;$v|Add-Member port $port
   if($port-eq8775){$responsive+=$v};if($width-in@(390,430,1440)){$heights+=$v;Cmd $ws ([ref]$n) 'Runtime.evaluate' @{expression="document.querySelector('#regions').scrollIntoView()"}|Out-Null;Start-Sleep -Milliseconds 150;$shot=Cmd $ws ([ref]$n) 'Page.captureScreenshot' @{format='png';fromSurface=$true;captureBeyondViewport=$false};[IO.File]::WriteAllBytes((Join-Path $out "regions-$width-$port.png"),[Convert]::FromBase64String($shot.result.data))}
  }
 }
 $styleExpr=@'
(()=>{const sels=['.home-school-finder','.school-province','.school-area-tabs button','.school-area-panel.is-active','.school-area-panel.is-active .school-link-grid','.school-area-panel.is-active .school-link-grid a'];return Object.fromEntries(sels.map(s=>{const e=document.querySelector(s),c=getComputedStyle(e);return[s,{display:c.display,width:c.width,height:c.height,padding:c.padding,margin:c.margin,gap:c.gap,fontSize:c.fontSize,border:c.border,borderRadius:c.borderRadius,background:c.backgroundColor,color:c.color}]}))})()
'@
 $schoolStyles=@{}
 foreach($width in @(1440,390)){foreach($port in @(8774,8775)){Cmd $ws ([ref]$n) 'Emulation.setDeviceMetricsOverride' @{width=$width;height=900;deviceScaleFactor=1;mobile=($width-lt768);screenWidth=$width;screenHeight=900}|Out-Null;Cmd $ws ([ref]$n) 'Page.navigate' @{url=("http://127.0.0.1:$port/")}|Out-Null;Start-Sleep -Milliseconds 500;$e=Cmd $ws ([ref]$n) 'Runtime.evaluate' @{expression=$styleExpr;returnByValue=$true};$schoolStyles["$width-$port"]=$e.result.result.value}}
 $schoolEqual=((ConvertTo-Json $schoolStyles['1440-8774'] -Compress -Depth 8)-eq(ConvertTo-Json $schoolStyles['1440-8775'] -Compress -Depth 8))-and((ConvertTo-Json $schoolStyles['390-8774'] -Compress -Depth 8)-eq(ConvertTo-Json $schoolStyles['390-8775'] -Compress -Depth 8))
 $clicks=@();foreach($group in @(1,2)){for($i=0;$i-lt10;$i++){Cmd $ws ([ref]$n) 'Page.navigate' @{url='http://127.0.0.1:8775/'}|Out-Null;Start-Sleep -Milliseconds 350;$sel="#regions>section:nth-of-type($group) .link-grid a:nth-child($($i+1))";$get=Cmd $ws ([ref]$n) 'Runtime.evaluate' @{expression="(()=>{const a=document.querySelector('$sel');const h=a.href;a.click();return h})()";returnByValue=$true};$expected=$get.result.result.value;Start-Sleep -Milliseconds 450;$loc=Cmd $ws ([ref]$n) 'Runtime.evaluate' @{expression='location.href';returnByValue=$true};$clicks+=@{group=if($group-eq1){'seoul'}else{'gyeonggi'};expected=$expected;actual=$loc.result.result.value;pass=($expected-eq$loc.result.result.value)}}}
 $result=@{responsive=$responsive;heights=$heights;school_computed_style_equal=$schoolEqual;clicks=$clicks};$result|ConvertTo-Json -Depth 10|Set-Content (Join-Path $out 'validation.json') -Encoding UTF8;$result|ConvertTo-Json -Depth 6;$ws.Dispose()
}finally{if($proc-and-not$proc.HasExited){Stop-Process $proc.Id -Force}}
